### ISSUE TITLE
update download instructions for dapps tutorials to use wget instead of curl

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna-docs#176]
On windows, downloading dapp-runner configs should be wget https://raw.githubusercontent.com/golemfactory/dapp-runner/main/configs/default.yaml -outfile config.yaml

**Comment by approxit** [comment]
As discussed offline, having kinda-linux command example crafted only for windows (where `wget` is alias for powershell's `Invoke-WebRequest`) could be confusing.

Let's use direct powershell syntax:
```
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/golemfactory/dapp-runner/main/configs/default.yaml" -OutFile "config.yaml"
```

Also, we could mention to download that file via graphical interface... :)
