### ISSUE TITLE
Windows: Can't follow the Hello World dApp tutorial

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna-docs#183]
The tutorial requires Docker to be installed on Windows. Technically speaking, that’s not possible. If someone is supposed to have Docker on Windows, they have to either use WSL2 or have a Hyper-V VM which will run a Linux distro that will have docker installed. Then the tutorial can be followed line by line with some difficulties. Namely, the reader has to configure the local environment once again (python, venv, dapp-runner, etc…, but inside the Linux VM (WSL2/Hyper-V) (previously they were going through the Windows installation steps, so here they have to start all-over again). The next one is that if someone is going to install WSL2, by default that’s a GUI-less distro, so putting code examples will require them to know vim/emacs etc.

### Todo
- List the changes that are required to have this example working on windows

https://golem-network.gitbook.io/golem-sdk-develop/requestor-tutorials/dapps/hello-world-dapp

**Comment by jalas167** [comment]
for windows I used:

python -m venv --clear %HOMEDRIVE%%HOMEPATH%\.envs\hello-dapps
%HOMEDRIVE%%HOMEPATH%\.envs\hello-dapps\scripts\activate


pip install -U pip poetry 
produces: 
ERROR: To modify pip, please run the following command:
C:\Users\golem\.envs\hello-dapps\Scripts\python.exe -m pip install -U pip poetry

then small change in:
mkdir  "hello_golem\server_app"

used curl https://raw.githubusercontent.com/golemfactory/dapp-runner/main/configs/default.yaml > golem_config.yaml
(missed the info about powershell)

after:

pip install dapp-runner

I get: 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 2.2.3 requires click>=8.0, but you have click 7.1.2 which is incompatible.


again different syntax for windows:
set YAGNA_APPKEY=<app key>  

dapp-runner start --config golem_config.yaml hello_golem.yaml

example with original image hash produced 500, with image created and uploaded to registry according to instructions - it worked.
