### ISSUE TITLE
Environment variable setting doesn't work on Windows

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna-docs#184]
The quick-start calls to run the dapp-runner using Linux like env passing, whic does not work on Windows

```
(dapps) C:\Users\ggodlewski\golem-test>YAGNA_APPKEY="692f68f2cd52427dbe320cb2bc9843f5" dapp-runner start --config config.yaml webapp.yaml
'YAGNA_APPKEY' is not recognized as an internal or external command,
operable program or batch file.
```

### Todo
- Prepare separate example for windows. It can be done in two steps instead of one.

**Comment by shadeofblue** [comment]
https://golem-network.gitbook.io/golem-sdk-develop/requestor-tutorials/dapps/run-a-dapp

**Comment by shadeofblue** [comment]
https://golem-network.gitbook.io/golem-sdk-develop/requestor-tutorials/dapps/hello-world-dapp

**Comment by lucekdudek** [comment]
We changed doc so this issue doesn't apply anymore
