### ISSUE TITLE
Add hint to user must belong to docker group before gvmkit-build works.

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/yagna-docs#2]
Doc over on Discord pointed out that it might be smart to let testers know that their machines user must belong to the docker group before the `gvmkit-build` command will work. It might save users some time troubleshooting in the future.

![image](https://user-images.githubusercontent.com/33448819/95248525-b2162d80-0817-11eb-8010-a23b158f8942.png)

**Comment by shadeofblue** [comment]
closing via https://github.com/golemfactory/yagna-docs/commit/adfda60b0e151f3ed4506bcdd5c985071ab73def
