### ISSUE TITLE
handbook - add tip when to import ID

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-docs#23]
2rec - handbook amendment request: add a tip when to import id (with mainnet funds). Two ppl from within Golem misunderstand our notion page, so it will help us internally at least, and I belive it will not hurt community readers, as they may also want to do this.

**Comment by maaktweluit** [comment]
for sure!

- On the mainnet guide when importing your key
- after you restarted the deamon and checked if the key was properly imported
- we should add a hint or when the key is "locked" to call `yagna id unlock`

**Comment by maaktweluit** [comment]
@shadeofblue sorry, i was wrong, this is about unlock! after my meeting i'll update the comment

**Comment by maaktweluit** [comment]
Updated

**Comment by tworec** [comment]
> After the first `yagna service start` we should add a hint: "If you want to use your own key-file.json now is the time to import it using this guide, before continueing this guide."

1. it is `yagna service run` not `start` :)
2. this comment above is exactly what I was thinking about. It was **not** about unlocking account, but hinting user when to import the key during installation.

**Comment by shadeofblue** [comment]
@tworec @maaktweluit would we like to add this to the Requestor's quick primer? if so, I'm unsure -> the guide is supposed to be the _quick_ start guide ... but maybe there's a place e.g. in the "Using Golem on Mainnet" section that would be better suited to carry such content? ... anyway, maybe I'm mistaken and you meant some other place for this piece

**Comment by tworec** [comment]
I was thinking about adding this somewhere within this paragraph https://handbook.golem.network/requestor-tutorials/flash-tutorial-of-requestor-development#purge-the-stale-working-directories

**Comment by shadeofblue** [comment]
okay, I still think that the "quick primer" for requestors is _not_ the place to put this instruction into... it's bloated already for something that should be super-focused and simple - this is the _first_ thing someone's doing with Golem - they _don't_ need to know about mainnet yet - they just want to see how easy it is to run Golem
