### ISSUE TITLE
Documentation's "Troubleshooting" section for requestors should contain a troubleshooting hint about the erc20 fallback

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna-docs#28]

**Comment by mateuszsrebrny** [comment]
@cryptobench how is this going?
Is this the requested change? https://handbook.golem.network/troubleshooting/common-issues#payment-driver-initialization-issue

Can we close the issue, or is there anything else to do here?

**Comment by cryptobench** [comment]
I think that the current documentation about payment driver initialization that you've linked is sufficient enough. Adding more info about the `--network mainnet` option may just clutter the section and confuse more than it helps. Requestors probably will know that they should add that argument if their issue is on mainnet.
