### ISSUE TITLE
State clearly in docs that ENTRYPOINT from docker image is overridden when compiling with gvmkit

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna-docs#46]

**Comment by shadeofblue** [comment]
@zakaprov please review: https://app.gitbook.com/@golem-network/s/golem-sdk-develop/~/drafts/-Mb_L6nyj1mAfXSHlOIp/requestor-tutorials/task-processing-development/hello-world

**Comment by zakaprov** [comment]
Not sure if we need this part of the second paragraph:
```
(...) any initialization that you need to make after the image is deployed and started on the provider's VM, must be done explictly with a separate execution script command sent from the requestor agent.
```
I feel like it's not providing much value to the reader at this point and may be unnecessarily discouraging.

**Comment by shadeofblue** [comment]
> Not sure if we need this part of the second paragraph:
> 
> ```
> (...) any initialization that you need to make after the image is deployed and started on the provider's VM, must be done explictly with a separate execution script command sent from the requestor agent.
> ```
> 
> I feel like it's not providing much value to the reader at this point and may be unnecessarily discouraging.

hmm... i feel like we're giving a solution to a problem we just identified ... otherwise, we'd leave the reader with a question "okay, so they took my entrypoint, what do I do now?"

**Comment by zakaprov** [comment]
Fair point, then perhaps let's make this less verbose, something like:
```
Instead, you can send a script execution command from the requestor agent (`context.run`). This will be demonstrated in the next step of this tutorial.
```
What do you think?

**Comment by shadeofblue** [comment]
@zakaprov adjusted accordingly

closing via: https://github.com/golemfactory/yagna-docs/commit/b4f55e17391bf9f33e67217c7617d8c3e9176481
