### ISSUE TITLE
State in docs that commands in the VM runtime exe unit are run without shell so passing full executable path is required

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna-docs#47]

**Comment by shadeofblue** [comment]
@zakaprov 

https://app.gitbook.com/@golem-network/s/golem-sdk-develop/~/drafts/-MbaHE7rIvKJLLdZx1Yw/requestor-tutorials/task-processing-development/hello-world

**Comment by zakaprov** [comment]
In the hashcat example I'd propose the following change:
```
Commands are passed to an explicitly-referenced /bin/sh shell. That's because any commands specified within ctx.run() are not, by themselves, run inside any shell.
```
(essentially just dropping the first few words)

**Comment by zakaprov** [comment]
In the hash cracker example:
```
call to the VM execution unit must directly refer to a given executable
```
Perhaps let's mention that this usually means an absolute path?

**Comment by shadeofblue** [comment]
resolved via https://github.com/golemfactory/yagna-docs/commit/c93c2ddfda8615bb29021401c75d31b8c63635af
