### ISSUE TITLE
Describe in docs (common issues section) that transfer error means that upload location is not a volume. 

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna-docs#49]
https://www.notion.so/golemnetwork/Developer-experience-gunicorn-on-provider-e5f7c037768147d7a7619903e2a57018#8b3f180625404f4cb49535f0f5d9142b

**Comment by shadeofblue** [comment]
@zakaprov https://app.gitbook.com/@golem-network/s/golem-sdk-develop/~/drafts/-Mb_VjEWmHZlGG4LPsBx/troubleshooting/common-issues

**Comment by zakaprov** [comment]
Merged in gitbook.
