### ISSUE TITLE
Resolve issue that causes a developer to create multiple images

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna-docs#51]
Add a comment in Dockerfile in "Golem Hello World" above the line COPY worker.py /golem/entrypoint/ mentioning that during development it might be better to upload the code in runtime rather than bake it in the image

**Comment by shadeofblue** [comment]
@zakaprov https://app.gitbook.com/@golem-network/s/golem-sdk-develop/~/drafts/-MbaTqa3O1xgDHAMgaWB/requestor-tutorials/task-processing-development/hello-world

**Comment by zakaprov** [comment]
Merged in gitbook.
