### ISSUE TITLE
Remove obsolete section about not working multiprocessing from docs

### ISSUE THREAD

**Issue by johny-b** [golemfactory/yagna-docs#55]
It is no longer an issue:
https://github.com/golemfactory/yagna/issues/1354

But the troubleshooting section is still here:
https://golem-network.gitbook.io/golem-sdk-develop/troubleshooting/common-issues#multiprocessing-python-library-not-working-on-providers

**Comment by shadeofblue** [comment]
closing via https://github.com/golemfactory/yagna-docs/commit/adfda60b0e151f3ed4506bcdd5c985071ab73def
