### ISSUE TITLE
the wallet restoration instructions assume linux+requestor

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-docs#58]
Name: blue
handbook

[https://handbook.golem.network/payments/using-golem-on-mainnet#restoring-your-backed-up-golem-wallet](https://handbook.golem.network/payments/using-golem-on-mainnet#restoring-your-backed-up-golem-wallet)
we should probably link the appropriate provider/requestor installation docs there

**Comment by shadeofblue** [comment]
closing via https://github.com/golemfactory/yagna-docs/commit/adfda60b0e151f3ed4506bcdd5c985071ab73def
