### ISSUE TITLE
add the following to the VM part of the tutorial

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna-docs#71]
(excerpt from the yacat tutorial)...

On the provider side, all the content of the VOLUME directories is stored in the provider's os file system.
All the changes in other (non VOLUME mounted) container directories content are kept in RAM. The rest of the VM image file system (not changed, non VOLUME mounted) content is stored as VM image in the provider's os file system.

Please mind that tasks within a single worker instance - so effectively part of the same activity on a given provider node - run within the same virtual machine and share the contents of a VOLUME between each other.
That means that as long as the execution takes place on the same provider, and thus, on the same filesystem, files in the VOLUME left over from one task execution will be present in a subsequent run.

If your provider-side code creates large temporary files, you should store them in the directory defined as VOLUME. Otherwise, the large files will be stored in RAM. RAM usually has a capacity limit much lower than disk space.

**Comment by rad9k** [comment]
also pls add the following diagram

![tnm-docs-infographics-08 (1)](https://user-images.githubusercontent.com/17722988/129862236-d4e296b9-7c15-48c7-b4cf-844b775380dc.jpg)

**Comment by shadeofblue** [comment]
resolved via https://github.com/golemfactory/yagna-docs/commit/9fa7dbf8d7b0788d419594e8eb7df073cd25154e
